name: Terraform/OpenTofu via PR Comments

on:
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [synchronize]
    paths: ["**/*.tf*"]

jobs:
  tf:
    if: startsWith(github.event.comment.body, '-tf=') || contains(join(github.event.pull_request.labels.*.name), 'tf:')
    runs-on: ubuntu-latest

    permissions:
      actions: read # Required for downloading artifacts.
      contents: read # Required for checking out repository.
      id-token: write # Required for assuming AWS role.
      issues: read # Required for getting PR branch.
      pull-requests: write # Required for commenting on PR.
      statuses: write # Required for setting commit status.
    
    steps:
      - name: Provision TF
        id: tf
        env:
          TF_VAR_repo_fullname: "Jacob-Bordelon/personal-terraform"
        uses: devsectop/tf-via-pr-comments@v9
        with:
          cli_uses: "tofu"
          cli_version: "~1.6"
          
      - name: Echo TF outputs
        run: |
          echo "command: ${{ steps.tf.outputs.command }}"
          echo "plan_id: ${{ steps.tf.outputs.plan_id }}"
          echo "tf_fmt: ${{ steps.tf.outputs.tf_fmt }}"
          echo "tf_output: ${{ steps.tf.outputs.tf_output }}"
