name: Reusable Workflow

on: 
  workflow_call:
    inputs:
      working-dir:
        required: true
        type: string

jobs:
  tofu-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pwd