name: Some workflow

on:
  issue_comment:
    types: [created]

jobs:
  comment:
    # if: contains(github.event.comment.body, 'tofu plan')
    runs-on: ubuntu-latest
    steps:
      - name: Somethings Running
        run: |
          echo "Hello World"

      - name: Add comment to PR
        env:
          URL: ${{ github.event.issue.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl \
            -X POST $URL 
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "blah blah" }'