name: Some workflow

on:
  issue_comment:
    types: [created]

permissions:
  id-token: write
  contents: read 
  pull-requests: write
  issues: write

jobs:
  find-existing:
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: 'github-actions[bot]'
          body-includes: <!-- opentofu-bot -->

      - name: Create comment
        if: ${{ steps.fc.outputs.comment-id == '' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.issue.number }}
          edit-mode: replace
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
            <!-- opentofu-bot -->