name: 'Initalizalize multiple Modules'

on: pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - run: touch file.txt
      - run: ls

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - run: ls
