name: 'Apply'

on:
  pull_request:
    types:
      - closed

permissions:
  id-token: write
  contents: read 
  pull-requests: write
  issues: write

jobs:
  tofu-init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - run: tofu init

  tofu-plan:
    runs-on: ubuntu-latest
    needs: [tofu-init]
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - run: tofu init
      - name: 'Tofu Plan'
        id: plan
        env:
          TF_VAR_repo_fullname: 'Jacob-Bordelon/personal-terraform'
          TF_VAR_env_name: 'production'
        run: tofu plan -no-color -out plan.tfplan
      - name: Upload Plan to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tofu-plan
          path: plan.tfplan
          retention-days: 1
      

  tofu-apply:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [tofu-init, tofu-plan]
    environment: 'staging'
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - run: tofu init
      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tofu-plan

      - name: 'Tofu Apply'
        run: pwd