name: 'Plan'

on: 
  pull_request
  # :
    # paths-ignore:
    #   - '.github/**'

permissions:
  id-token: write
  contents: read 
  pull-requests: write
  issues: write

jobs:
  tofu-init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1
      - run: tofu init
  
  tofu-plan:
    runs-on: ubuntu-latest
    needs: [tofu-init]
    steps:
      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1
      - run: tofu init
      - name: 'Tofu Plan'
        id: plan
        env:
          TF_VAR_repo_fullname: 'Jacob-Bordelon/personal-terraform'
          TF_VAR_env_name: 'production'
        run: |
          tofu plan > tofu-plan.txt

      - name: Store text block as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tofu-plan
          path: tofu-plan.txt
          retention-days: 1

  comment:
    needs: [tofu-init, tofu-plan]
    runs-on: ubuntu-latest
    steps:
      - name: Download text block artifact
        uses: actions/download-artifact@v4
        with:
          name: tofu-plan

      - name: Set environment variable
        id: plan
        run: |
          cat tofu-plan.txt

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        continue-on-error: true
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: <!-- opentofu-bot -->

      - name: Create or Update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            <!-- opentofu-bot -->
            Terraform Plan
