name: 'Plan'

on: 
  pull_request
  # :
    # paths-ignore:
    #   - '.github/**'

permissions:
  id-token: write
  contents: read 
  pull-requests: write
  issues: write

jobs:
  tofu-init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1
  
  tofu-plan:
    runs-on: ubuntu-latest
    needs: [tofu-init]
    steps:
      - name: 'Tofu Plan'
        id: plan
        run: |
          echo "res=$(pwd)" >> $GITHUB_OUTPUT

    outputs:
      results: ${{ steps.plan.outputs.res }}

  comment:
    needs: [tofu-init, tofu-plan]
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        continue-on-error: true
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: <!-- opentofu-bot -->

      - name: Create or Update comment
        uses: peter-evans/create-or-update-comment@v4
        env:
          PLAN: ${{needs.tofu-plan.outputs.results }}
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            <!-- opentofu-bot -->
            Terraform Plan
            ```hcl
            ${{ PLAN }}
            ```