name: Terraform-Planner

on: 
  pull_request:
    branches:
      - staging

jobs:
  plan:
    name: plan
    runs-on: macos-latest
    steps:
      - name: install opentofu
        run: brew install opentofu
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run init
        run: tofu init
      - name: Run Plan
        run: tofu plan
