name: 'Approval - Staging'

on: pull_request

permissions:
  id-token: write
  contents: read 
  pull-requests: write
  issues: write

jobs:
  tofu-init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1
  
  tofu-plan:
    runs-on: ubuntu-latest
    needs: [tofu-init]
    steps:
      - name: 'Tofu Plan'
        run: pwd

  tofu-apply:
    runs-on: ubuntu-latest
    needs: [tofu-init, tofu-plan]
    environment: 'staging'
    outputs:
      approved: false
    steps:
      - name: 'Tofu Apply'
        continue-on-error: true
        run: pwd