name: 'Plan'

on: 
  pull_request:
    paths-ignore:
      - '.github/**'

permissions:
  id-token: write
  contents: read 
  pull-requests: write
  issues: write

jobs:
  tofu-init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1
  
  tofu-plan:
    runs-on: ubuntu-latest
    needs: [tofu-init]
    steps:
      - name: 'Tofu Plan'
        run: pwd